grid = """


　　五〇〇〇
　　　　仙
　　　　过
　　　　〇
"""
candidates = '八门花海'
[answers."八仙过海"]
meaning = "相传八仙过海时不用舟船，各有一套法术。民间因有“八仙过海，各显神通”的谚语。后以比喻各自拿出本领或办法，互相竞赛。"
example = "说得好，咱们就～吧！——老舍《茶馆》第一幕"

[answers."五花八门"]
meaning = "原指五行阵和八门阵，这是两种变化很多的阵势。比喻变化多端或花样繁多"
example = "湖北的省政府在当时真正是一种鱼龙漫衍的“模范政府”，那个委员会～地是什么人品都有。"
