# 9✖️9 格子
# 全角空格‘　’代表空白格，‘〇’代表待填字符
grid = [
"　　　　　　　　　",
"　　　　　　　　　",
"　　　　　　　　　",
"　　　　　〇正典刑",
"　　　　　　　则　",
"　　　〇　〇新〇逸",
"　　　然　心　〇　",
"　　　失道寡〇　　",
"　　　笑　欲　　　"]
candidates = "清雅助哑俊明欣舍"
answerPos = [50, 61, 69, 48, 52, 32, -1, -1]
